server {
    listen 80;

    # Root-Verzeichnis für die Webseite
    root /usr/share/nginx/html;

    # Standard-Datei, die geladen wird
    index index.html;

    # Location für CSS-Dateien
    location /css {
        alias /usr/share/nginx/html/css;
    }

    # Location für JavaScript-Dateien
    location /js {
        alias /usr/share/nginx/html/js;
    }

    location /webfonts {
        alias /usr/share/nginx/html/webfonts;
    }

    # Alle anderen Anfragen sollen auf die index.html zeigen
    location / {
        try_files $uri /index.html;
    }

    # Komprimierung aktivieren (optional, für bessere Performance)
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_min_length 1024;

    # Caching-Header hinzufügen (optional)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
    }
}
